@startuml artifacts-r303-bis
!include config-min.cfg

class "User Story" as US

Requirement <. US: << concern >>
' US <.. Issue: << sastisfy >>
US <.. Feature: << sastisfy >>
Feature  <.. Issue: << sastisfy >>
Release "1" -> "*" Issue
Issue "1" -> "*" Task

Task <|-- Code
Task <|-- Test
Task <|-- Doc

Code <. Test : <<verify>>

@enduml