@startuml

'-----------------------------------
' UML patterns illustrated
' JMB 2014
'-----------------------------------

state E1
E1 --> Destination : événement1
E2 --> Destination : événement2
Destination : entry / action

@enduml
