@startuml

'-----------------------------------
' UML patterns illustrated
' JMB 2014
'-----------------------------------

[*] --> normal
state "Fonctionnement \nNormal" as normal {
  [*] -> Vert
  Vert -> Orange
  Orange -> Rouge
  Rouge -> Vert
}
state "En panne" as panne {
  state Clignotant
}

normal --> panne : probleme
panne --> normal : reparation

@enduml
