@startuml

'-----------------------------------
' UML concepts illustrated
' JMB 2014
'-----------------------------------

'hide circle
hide empty members
hide empty methods


interface Cancaneur {
cancaner()
}

interface Volant {
voler()
}

abstract class Canard {
nager()
afficher()
}

class Colvert {
afficher()
voler()
cancaner()
}

class Mandarin {
afficher()
voler()
cancaner()
}

class CanardEnPlastique {
afficher()
cancaner()
}

class Leurre {
afficher()
}


@enduml
