@startuml
'-----------------------------------
' Template PlantUML drawing 
' JMB 2017
'-----------------------------------
' PlantUML stdlib now includes Icon-Font Sprites! See https://github.com/tupadr3/plantuml-icon-font-sprites
' see also https://tupadr3.de/plantuml-icon-font-sprites/
!define ICONURL https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/v1.0.0

!include Defs.txt
'!define DATE %date[yyyy.MM.dd 'at' HH:mm]%
!define DATE %date[yyyy.MM.dd]%

'----------------------------------- mise en page
'scale 180*90
scale 1.5

'skinparam monochrome true

'skinparam defaultFontColor red 
'skinparam defaultFontSize 10 
skinparam defaultFontName Yanone+Kaffeesatz

skinparam titleBorderRoundCorner 30
skinparam titleBorderThickness 1
skinparam titleBorderColor red
skinparam titleBackgroundColor Aqua-CadetBlue

title Drawing Template

legend right
This is a legend
endlegend

caption This is a caption

header
<font color=red>Warning!</font>
Do not use in production.
endheader

center footer (c) JMB -- Last update DATE

'-----------------------------------

!includeurl ICONURL/common.puml
!includeurl ICONURL/font-awesome/server.puml
!includeurl ICONURL/font-awesome/database.puml
!includeurl ICONURL/font-awesome/gitlab.puml


FA_SERVER(web1,libweb1,cloud) #Green
FA_SERVER(web2,web2) #Gold
FA_SERVER(web3,web3) #SkyBlue
FA_SERVER(web4,web4) #YellowGreen

skinparam rectangleRoundCorner 15

rectangle "foo" #LightBlue {
    FA_DATABASE(db1,LIVE,storage,white) #DodgerBlue
    FA_GITLAB(db3,GITLAB,file) #LightCyan
    db1 <--> db3
}
'end box

FA_DATABASE(db2,SPARE,node) #Red

db1 --> db2

web1 -up-> db1
web2 -right-> db1
web3 -left-> db1
web4 <--> db1

note left
  This is **bold**
  This is //italics//
  This is ""monospaced""
  This is --stroked--
  This is __underlined__
  This is ~~waved~~
end note

@enduml