name: Checks

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: 'config.json'

  asciidoc-link-check:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g asciidoc-link-check
    # - run: asciidoc-link-check README.adoc -c config.json
    # - run: asciidoc-link-check CONTRIBUTING.adoc -c config.json
    # - run: asciidoc-link-check git.adoc -c config.json
    # - run: asciidoc-link-check intro.adoc -c config.json
    # - run: asciidoc-link-check refactoring.adoc -c config.json
    # - run: asciidoc-link-check requirements.adoc -c config.json
    # - run: asciidoc-link-check test.adoc -c config.json
    # - run: asciidoc-link-check testingCI.adoc -c config.json
    - run: find . -name \*.adoc -exec asciidoc-link-check -c config.json {} \;